language: node_js
node_js:
  - "22"

branches:
  only:
    - master

before_script:
  - npm install

script:
  - npm run builddocs

notifications:
  email:
    on_failure: change
    on_success: change

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master

notifications:
  email:
    on_failure: change
    on_success: change

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master