language: node_js
node_js:
  - "8.9"

branches:
  only:
    - master

before_script:
  - npm install -g angular-cli
  - npm install

script:
  - ng build --bh /siskiyou/
  - rimraf docs
  - copyfiles -u 1 dist/** docs

notifications:
  email:
    on_failure: change
    on_success: change

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master