language: node_js
node_js:
  - "8.9"

branches:
  only:
    - master

before_script:
  - npm install -g angular-cli
  - npm install

script:
  - ng build --prod --aot false

notifications:
  email:
    on_failure: change
    on_success: change
